services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "3000:3000"
  db:
    image: postgres:17.5
    container_name: fullstack_db
    env_file:
      - .env.development
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
